# Generated by Django 2.2 on 2019-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Book Title')),
                ('price', models.IntegerField(default='', verbose_name='Book Price')),
                ('memo', models.TextField(blank=True, default='', verbose_name='Book Memo')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Created Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
            ],
        ),
    ]
